[tool.black]
exclude = '''
(
  \.git
)
'''
line-length = 79


# [tool.flake8]
#   config: .flake8
# also see: https://gitlab.com/pycqa/flake8/-/issues/428


[tool.isort]
import_heading_firstparty = 'First-party/Local'
import_heading_future = 'Future'
import_heading_stdlib = 'Standard library'
import_heading_thirdparty = 'Third-party'
line_length = 79
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
profile = 'black'
